<?php
namespace Slim\Controller\Test;

use Slim\Controller\AppController;


class IndexController
{
    public function index()
    {

    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-12 at 07:39:58.
 */
class AppControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AppController
     */
    protected $app;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->app = new AppController();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Slim\Controller\AppController::createController
     * @todo   Implement testCreateController().
     */
    public function testCreateController()
    {
        $controller = $this->app->createController('\Slim\Controller\Test\IdexControllr:index');
    }

    /**
     * @covers Slim\Controller\AppController::urlForBase
     * @todo   Implement testUrlForBase().
     */
    public function testUrlForBase()
    {
        $this->app->get('/', function() {})->name('base');
        echo $this->app->urlForBase();
    }
}
